import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { CardItem } from '../components/CardItem'
import { Landing } from '../components/Landing'
import { Navbar } from '../components/Navbar'
import img from '../public/imgs/lace.jpg'
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Visit Pakistan</title>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;300;400;500;600;700;800&family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet"/> 
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-blue-200'>
      <Navbar/>
      <Landing/>
      </div>
      <div className="bg-[url('../public/imgs/lace.jpg')] bg-contain h-[80px] w-full " ></div>
      <div>
        <h4 className='text-sm font-heading my-10 text-center w-full tracking-[10px] font-semibold'>POPULAR ACTIVITIES</h4>
        <h3 className='text-4xl my-10 tracking-wide w-full text-center capitalize font-medium'>Most popular activities in pakistan</h3>
        <CardItem/>
      </div>
    </div>
  )
}

export default Home
